# Generated by Django 5.2.4 on 2025-07-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cleint_email',
            new_name='client_email',
        ),
    ]
